spring:
  application:
    name: aca-used-goods
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:7NDBdL9Qu4rOhQhDG2eA58RWw2mkbyG09pSOaER68XurUlF5xcAfgGusXEAlOXPej1uY8OwBu5G+WF7sWKeGjg==}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
